openapi: 3.0.3
info:
  title: Search engine api
  description: |
    This documentation is for simple search engine built with node.js, express and elasticsearch.
    The search engine have different capabilities.
    1. fuzzy search
    2. full sentence search
    3. regexp search for completing unfinished words
    4. full match search to find the exact match
    5. Can sort using images position field
    6. can search in different language by translating users input to english
    
  version: 1.0.0
servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/EBRIMAJORBARTEH_1/search-engine/1.0.0
  - url: https://search-ud2e.onrender.com/
paths:
  /api/search:
    get:
      operationId: db00175f-4b26-404e-ba5c-450040f1935c
      description: Search using by query input from json body
      parameters:
        - name: query
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Search using query field in json
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  data:
                    type: array
                    items:
                      type: string
    post:
      operationId: 5a26b8e5-1944-4273-8501-4435bf122b32
      description:  Search using by query input from json body
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: POST /api/search/
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _index:
                          type: string
                        _id:
                          type: string
                        _score:
                          type: string
                        _source:
                          type: object
                          properties:
                            title:
                              type: string
                            tags:
                              type: string
                            picture:
                              type: string
                            position:
                              type: string
  /api/search/sort:
    post:
      operationId: 914297b7-e8b0-4a21-8364-d6b638c967c1
      tags:
        - sort
      description: Search using query json body request and sort results by using their position
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: POST /sort
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  data:
                    type: array
                    items:
                      type: string
    get:
      operationId: b5478fa8-8526-4c73-85e4-30dd73323e1f
      tags:
        - sort
      description: Search using query json body request and sort results by using their position
      parameters:
        - name: query
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: GET /sort
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _index:
                          type: string
                        _id:
                          type: string
                        _score:
                          type: string
                        _source:
                          type: object
                          properties:
                            title:
                              type: string
                            tags:
                              type: string
                            picture:
                              type: string
                            position:
                              type: string
  /api/search/translate:
    get:
      operationId: 3e2d8987-5839-45df-aae6-f4bf4d3e3c31
      tags:
        - translate
      description: Search by translating users input term using user specified language
      parameters:
        - name: query
          in: query
          required: false
          schema:
            type: string
        - name: lang
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: GET /translate
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _index:
                          type: string
                        _id:
                          type: string
                        _score:
                          type: string
                        _source:
                          type: object
                          properties:
                            title:
                              type: string
                            tags:
                              type: string
                            picture:
                              type: string
                            position:
                              type: string
    post:
      operationId: 88efc6cb-8fba-433e-a309-2f227047c399
      tags:
        - translate
      description: Search by translating users input term using user specified language
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                query:
                  type: string
                lang:
                  type: string
      responses:
        '200':
          description: POST /api/translate
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _index:
                          type: string
                        _id:
                          type: string
                        _score:
                          type: string
                        _source:
                          type: object
                          properties:
                            title:
                              type: string
                            tags:
                              type: string
                            picture:
                              type: string
                            position:
                              type: string
